# Generated by Django 4.2.3 on 2023-07-11 11:50

from django.db import migrations

def dump_data(apps, schema_editor):
    from django.contrib.auth import get_user_model

    CustomUser = get_user_model()
    user_admin = CustomUser.objects.create(
            username='admin',
            first_name='System',
            last_name='Admin'
        )
    user_admin.is_admin=True
    user_admin.is_staff=True
    user_admin.set_password('administrador')
    user_admin.save()

    user_admin = CustomUser.objects.create(
            username='normaluser',
            first_name='Normal',
            last_name='User'
        )
    user_admin.set_password('normaluser')
    user_admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dump_data)
    ]
