services:


  backend:
    container_name: react-django-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    ports:
      - "8888:8888"
    
  frontend:
    container_name: react-django-frontend
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app/frontend
      # - /app/frontend/node_modules
    env_file:
      - ./frontend/.env
    command: sh -c "npm rebuild esbuild && npm run dev"
    ports:
      - "5555:5555"
    depends_on:
      - backend
